### 프로퍼티 암호화
POST http://localhost:8888/encrypt
Content-Type: text/plain

beyond

### 프로퍼티 복호화
POST http://localhost:8888/decrypt
Content-Type: text/plain

6a23e190d0728c203f26bb92ce11f075da123a7c079bdbc3240e2c8dac1d1baa

